dist: xenial
language: python
python:
  # https://docs.python.org/devguide/#status-of-python-branches
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
before_install: pip install codecov
install: pip install --upgrade -r dev_requirements.txt
script: PYTHONHASHSEED=random pytest
after_success: codecov
