sudo: false
language: python
python:
  # https://docs.python.org/devguide/#status-of-python-branches
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
before_install: pip install codecov
install: pip install -r dev_requirements.txt
script: py.test
after_success: codecov
