sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
before_install: pip install codecov
install: pip install -r dev_requirements.txt
script: py.test
after_success: codecov
